### ISSUE TITLE
The first connection to a docker based Strapi has the hostname and port wrong

### ISSUE THREAD

**Issue by asitemade4u** [strapi/strapi-docker#192] opened 2020-03-31 20:53 UTC
Here is how to reproduce:

1. Create a docker-compose file with a different Strapi port, eg.:
     ```
       ports:
            - "1338:1337"
    ```
1. and a different hostname than `localhost`, eg.:
    ``` 
       environment:
               - HOST=<my_hostname>.com
   ```
1. At first opening and admin user creation, the browser opens on: `localhost:1337` whch yields a 404.
1. The solution is simple (change the URL manually), but may distress users not used to docker.

**Comment by alexandrebodin** [comment] 2020-04-01 07:42
Hi, this issue is a duplicate of https://github.com/strapi/strapi-docker/issues/192

**Closed by alexandrebodin** 2020-04-01 07:42 UTC

**Comment by ruisilvestre** [comment] 2020-04-01 10:38
^ this **is** issue 192 :D did you mean 191?
