### ISSUE TITLE
Dependencies install at run time

### ISSUE THREAD

**Issue by bluehawk27** [strapi/strapi-docker#201] opened 2020-04-26 17:04 UTC
The current implementation looks like it installs the deps in the container at run time. Consider moving this to build time. From within an ECS cluster the call to fontawesome currently fails because its trying to make an https call. I'd rather not open the instance to https traffic to the outside world

**Comment by alexandrebodin** [comment] 2020-04-27 09:15
Hi, The script strapi/strapi image creates a new project if you don't provide one and runs it if one is mounted. It installs the dependencies only when creating the project. 

When go to production, you should you the strapi/base image and build your own Dockerfile like you can find in the examples folder :) 


I'm closing the issue as it is the intended behavior

**Closed by alexandrebodin** 2020-04-27 09:15 UTC
