### ISSUE TITLE
Deploy latest image on docker hub

### ISSUE THREAD

**Issue by botzill** [strapi/strapi-docker#123] opened 2019-06-13 04:56 UTC
Hi.

I noticed that docker hub version is always behind the official release. Can we make some kind of automation keep them in sync? 

Thx.

**Comment by apollocoder** [comment] 2019-06-14 15:36
I forked the repo and added support for strapi@beta: 

https://github.com/apollocoder/strapi-docker

Had to include some dubious `npm rebuild` to get the admin build working (`strapi build`). Feedback would be very welcomed! :)

**Comment by secretlifeof** [comment] 2019-06-15 12:39
@apollocoder thank you. Have you tested your docker setup with postgreSQL 11? In the admin panel the first user is not added, I cannot add any more users and the administration role is missing.

Any thoughts on the cause of this?

See #121 

I have tested this on local machine and on Kubernetes, production and development env with same results.

**Comment by apollocoder** [comment] 2019-06-17 08:12
@secretlifeof No, I'm sorry. We're using mongo at the moment and I don't have the resources to test it with other providers.

**Comment by rrubio** [comment] 2019-06-18 22:54
Hi Guys!

Will docker be upgraded to beta soon?

**Comment by mastix** [comment] 2019-07-10 13:41
> I forked the repo and added support for strapi@beta:
> 
> https://github.com/apollocoder/strapi-docker

Cool stuff. Thanks. You should update the README with the correct clone URL. I've almost copied the wrong URL. :)

**Comment by apollocoder** [comment] 2019-07-16 12:42
@mastix Thanks! :) I've just updated the url.

**Comment by imbr** [comment] 2019-07-17 13:34
@lauriejim Hello, when can we expect a new version with strapi@beta? ;)

**Comment by promek** [comment] 2019-07-28 21:26
Hi,
@apollocoder,  I reviewed https://github.com/apollocoder/strapi-docker.
I set the default setting of DATABASE_CLIENT parameter to sqlite.
I added the START_PARAMS parameter. so it can be used as a dev/start, 
and I've uploaded the docker file to https://hub.docker.com/r/promek/strapi.
For sqlite it can simply be executed like this:
docker run -d --name apitest \
    -v strapi-app:/usr/src/api \
    -p 1337:1337 \
    promek/strapi:beta

you can also review the files at https://github.com/promek/dockers/tree/master/strapi.
I hope that will be useful.

**Comment by tomeady** [comment] 2019-08-01 13:29
updates?

**Comment by botzill** [comment] 2019-08-21 08:20
Hi guys. 

Any updates on this one? We really need the latest version on docker hub.

Thx.

**Comment by daehruoydeef** [comment] 2019-09-19 10:40
I also updated the Docker container and it is working fine so far, any updates when this becomes official?

**Comment by alexandrebodin** [comment] 2019-10-23 08:34
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯

**Closed by alexandrebodin** 2019-10-23 08:34 UTC
