### ISSUE TITLE
Could not use with AWS ECS containers

### ISSUE THREAD

**Issue by S-Polimetla** [strapi/strapi-docker#25] opened 2018-05-30 17:17 UTC
I tried using the compose file along with ECS CLI to deploy the containers into  ECS cluster. It creates and run the cluster but I could not access the public IP of the container instance at port 1337. It just times out. 

I tried running this docker-compose up locally and it works. 

Just wondering what additional criteria I would have to go if I am running in the cloud.

**Comment by lucaperret** [comment] 2018-05-30 17:44
Hello @sriharsha186, you could configure the `HOST` environment variable with the public IP.

**Comment by sriharsha186** [comment] 2018-05-30 20:21
{
  "executionRoleArn": null,
  "containerDefinitions": [
    {
      "dnsSearchDomains": [],
      "logConfiguration": null,
      "entryPoint": [],
      "portMappings": [
        {
          "hostPort": 80,
          "protocol": "tcp",
          "containerPort": 1337
        }
      ],
      "command": [],
      "linuxParameters": {
        "capabilities": {
          "add": null,
          "drop": null
        },
        "sharedMemorySize": null,
        "tmpfs": null,
        "devices": null,
        "initProcessEnabled": null
      },
      "cpu": 10,
      "environment": [
        {
          "name": "APP_NAME",
          "value": "strapi-app"
        },
        {
          "name": "DATABASE_CLIENT",
          "value": "mongo"
        },
        {
          "name": "DATABASE_HOST",
          "value": "db"
        },
        {
          "name": "DATABASE_NAME",
          "value": "strapi"
        },
        {
          "name": "DATABASE_PASSWORD",
          "value": ""
        },
        {
          "name": "DATABASE_PORT",
          "value": "27017"
        },
        {
          "name": "DATABASE_USERNAME",
          "value": ""
        },
        {
          "name": "HOST",
          "value": "**my public ip**"
        }
      ],
      "ulimits": null,
      "dnsServers": [],
      "mountPoints": [
        {
          "readOnly": false,
          "containerPath": "/usr/src/api/strapi-app",
          "sourceVolume": "volume-0"
        }
      ],
      "workingDirectory": null,
      "dockerSecurityOptions": [],
      "memory": 512,
      "memoryReservation": null,
      "volumesFrom": [],
      "image": "strapi/strapi",
      "disableNetworking": null,
      "healthCheck": null,
      "essential": true,
      "links": [
        "db"
      ],
      "hostname": null,
      "extraHosts": null,
      "user": null,
      "readonlyRootFilesystem": false,
      "dockerLabels": null,
      "privileged": false,
      "name": "api"
    },
    {
      "dnsSearchDomains": [],
      "logConfiguration": null,
      "entryPoint": [],
      "portMappings": [
        {
          "hostPort": 27017,
          "protocol": "tcp",
          "containerPort": 27017
        }
      ],
      "command": [],
      "linuxParameters": {
        "capabilities": {
          "add": null,
          "drop": null
        },
        "sharedMemorySize": null,
        "tmpfs": null,
        "devices": null,
        "initProcessEnabled": null
      },
      "cpu": 10,
      "environment": [
        {
          "name": "MONGO_INITDB_DATABASE",
          "value": "strapi"
        }
      ],
      "ulimits": null,
      "dnsServers": [],
      "mountPoints": [
        {
          "readOnly": false,
          "containerPath": "/data/db",
          "sourceVolume": "volume-2"
        }
      ],
      "workingDirectory": null,
      "dockerSecurityOptions": [],
      "memory": 512,
      "memoryReservation": null,
      "volumesFrom": [],
      "image": "mongo",
      "disableNetworking": null,
      "healthCheck": null,
      "essential": true,
      "links": [],
      "hostname": null,
      "extraHosts": null,
      "user": null,
      "readonlyRootFilesystem": false,
      "dockerLabels": null,
      "privileged": false,
      "name": "db"
    }
  ],
  "placementConstraints": [],
  "memory": null,
  "taskRoleArn": "arn:aws:iam::**myaccount**:role/ecsTaskExecutionRole",
  "compatibilities": [
    "EC2"
  ],
  "taskDefinitionArn": "arn:aws:ecs:eu-central-1:**myaccount**:task-definition/sriharsha:13",
  "family": "sriharsha",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    }
  ],
  "requiresCompatibilities": [
    "EC2"
  ],
  "networkMode": "bridge",
  "cpu": null,
  "revision": 13,
  "status": "ACTIVE",
  "volumes": [
    {
      "name": "volume-2",
      "host": {
        "sourcePath": "/db"
      }
    },
    {
      "name": "volume-0",
      "host": {
        "sourcePath": "/strapi-app"
      }
    },
    {
      "name": "volume-1",
      "host": {
        "sourcePath": "/usr/src/api/strapi-app/node_modules"
      }
    }
  ]
}

**Comment by sriharsha186** [comment] 2018-05-30 20:29
You mean the port here? Instead of 1337?

{
"executionRoleArn": null,
"containerDefinitions": [
{
"dnsSearchDomains": [],
"logConfiguration": null,
"entryPoint": [],
"portMappings": [
{
"hostPort": 80,
"protocol": "tcp",
"**_containerPort": 1337_**
}
],

**Comment by sriharsha186** [comment] 2018-05-30 20:52
I wonder how that would resolve but tried it nevertheless and the new task definition with container port as 80.  I am afraid, the issue stays unresolved.

**Comment by sriharsha186** [comment] 2018-05-30 21:37
Thank you @lucaperret  for the quick response.  I tried changed the HOST to the public IP of the running EC2 instance but the result is the same. :(

**Comment by sriharsha186** [comment] 2018-05-30 21:38
Oops. Closed by mistake

**Comment by lucaperret** [comment] 2018-05-31 05:19
You can try also to define the `PORT` environment variable to `80` in your container.

**Comment by sriharsha186** [comment] 2018-06-04 14:27
Removing HOST completely worked for me.

**Comment by sriharsha186** [comment] 2018-06-12 18:51
Since this is a related issue, I am reopening. 

Informations

**Node.js version: 8.10
npm version:
Strapi version: alpha.12
Database: mongo
Operating system: Linux Image**

**What is the current behavior?**
A content type with images and Relations has been created. Each time a image is uploaded and saved, it gives the error as this.updateRelation is not a function. It saves the text and other content however.´ But only when creating for the first time.

If these fields are updated at the later time, the error occurs and fields are not saved.

**Steps to reproduce the problem**
Create a task definition on AWS ECS with mongo and strapi as containers. Run the task.

**What is the expected behavior?**
Images should be saved, update is possible at a later time.

**Suggested solutions**
I have seen that there is a new version 12.3 which possibly fixed this issues but the docker image strapi/strapi still uses version 12. If the above mentioned bugs are fixed in 12.3, it would be great if the docker image is update on dockerhub.

**Comment by lucaperret** [comment] 2018-06-14 20:15
Could you retry with the last docker image that includes the v3.0.0-alpha.12.4 ?

**Comment by sriharsha186** [comment] 2018-06-18 10:56
I deployed a container with the same task definition as before (with alpha.12) and just changed the tag as v3.0.0-alpha.12.4 instead of latest (just to rule out possibility of caching).  I could not access with the public IP of the EC2 instance.  To cross check, I deployed a different cluster with tag v3.0.0-alpha.12 and it works fine. 

All the configuration is exactly the same with both of these instances except for the image tag.

**Comment by lucaperret** [comment] 2018-08-02 06:17
Could you report it to the core Strapi's package?

**Comment by lauriejim** [comment] 2019-03-21 17:11
Can you give us an update please.
Based on last version of files.

**Comment by alexandrebodin** [comment] 2019-10-23 08:41
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯

**Closed by alexandrebodin** 2019-10-23 08:41 UTC
