### ISSUE TITLE
Everything runs but cannot connect from host (MacOS Catalina)

### ISSUE THREAD

**Issue by rmcsharry** [strapi/strapi-docker#190] opened 2020-03-30 23:21 UTC
I followed the readme twice and both times everything installs and runs, as you can see:

![Screenshot 2020-03-31 at 01 17 59](https://user-images.githubusercontent.com/1156100/77970885-a2a8ab80-72ed-11ea-895b-0613bce24bd5.png)

but when I visit http://localhost:1337/admin nothing renders.

![Screenshot 2020-03-31 at 01 19 55](https://user-images.githubusercontent.com/1156100/77970942-c10ea700-72ed-11ea-9502-8edb8e831885.png)

I opened a bash shell inside the container, just to check and ran `strapi build`, which ran, but still no dice, and it tells me that strapi is indeed running:

![Screenshot 2020-03-31 at 01 22 43](https://user-images.githubusercontent.com/1156100/77971160-48f4b100-72ee-11ea-96bf-9a2019a35f34.png)

Ideas?

**Comment by ktryndchrs** [comment] 2020-03-31 03:30
I have the same exact problem here 😅. I tryed every installation method possible with always the same result

**Comment by alexandrebodin** [comment] 2020-03-31 09:23
Going to closing this as a duplicate of. This is the same issue :) https://github.com/strapi/strapi-docker/issues/191

**Closed by alexandrebodin** 2020-03-31 09:23 UTC
